version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: hunt-duck-game
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
